#!/bin/bash
set -e

echo "=== Aplicar Migration platform_fee_percentage no RDS PROD ==="
echo ""
echo "OPÇÃO 1: Via ECS Task (recomendado)"
echo "----------------------------------------"
echo "aws ecs run-task \\"
echo "  --cluster kaviar-prod-cluster \\"
echo "  --task-definition kaviar-backend-migration \\"
echo "  --launch-type FARGATE \\"
echo "  --network-configuration 'awsvpcConfiguration={subnets=[subnet-xxx],securityGroups=[sg-xxx],assignPublicIp=ENABLED}' \\"
echo "  --overrides '{\"containerOverrides\":[{\"name\":\"backend\",\"command\":[\"sh\",\"-c\",\"npx prisma migrate deploy\"]}]}' \\"
echo "  --region us-east-2"
echo ""
echo "OPÇÃO 2: Via SQL direto (se tiver acesso ao RDS)"
echo "----------------------------------------"
echo "psql \"\$DATABASE_URL\" -f backend/migrations/add_metrics_fields.sql"
echo ""
echo "OPÇÃO 3: Via Bastion/Jump Host"
echo "----------------------------------------"
echo "# SSH para bastion que tem acesso ao RDS"
echo "ssh -i ~/.ssh/kaviar-bastion.pem ec2-user@<bastion-ip>"
echo "# Dentro do bastion:"
echo "psql -h kaviar-prod-db.cxuuaq46o1o5.us-east-2.rds.amazonaws.com -U kaviaradmin -d kaviar -f add_metrics_fields.sql"
echo ""
echo "=== Verificação Pós-Migration ==="
echo "psql \"\$DATABASE_URL\" -c \"SELECT column_name, data_type FROM information_schema.columns WHERE table_name='rides' AND column_name='platform_fee_percentage';\""
